/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test Jav-maven using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=retryTemplate_ac1bcf3927
ROOST_METHOD_SIG_HASH=retryTemplate_52e0568e29

Scenario 1: Verify RetryTemplate Configuration with Valid Properties

Details:
  TestName: verifyRetryTemplateConfigurationWithValidProperties
  Description: This test checks if the RetryTemplate is correctly configured when valid SpringAiRetryProperties are provided. It ensures that the maxAttempts, retryOn exceptions, and exponentialBackoff settings are applied as expected.
Execution:
  Arrange: Create a mock of SpringAiRetryProperties with specific maxAttempts and backoff settings. Set up the necessary exception classes.
  Act: Call the retryTemplate method with the mocked properties.
  Assert: Verify that the RetryTemplate is configured with the correct maxAttempts, retryOn exceptions, and exponentialBackoff settings.
Validation:
  This assertion verifies that the RetryTemplate is correctly initialized with the provided properties, ensuring that retries are attempted according to the specified configuration. This is crucial for handling transient errors effectively in the application.

*/

// ********RoostGPT********

package org.springframework.ai.retry.autoconfigure;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.ai.retry.TransientAiException;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.retry.RetryCallback;
import org.springframework.retry.RetryContext;
import org.springframework.retry.RetryListener;
import org.springframework.retry.support.RetryTemplate;
import org.springframework.retry.support.RetryTemplateBuilder;
import org.springframework.web.client.ResourceAccessException;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.*;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.retry.NonTransientAiException;
import org.springframework.ai.retry.RetryUtils;
import org.springframework.boot.autoconfigure.AutoConfiguration;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.http.client.ClientHttpResponse;
import org.springframework.lang.NonNull;
import org.springframework.util.CollectionUtils;
import org.springframework.util.StreamUtils;
import org.springframework.web.client.ResponseErrorHandler;

@SpringBootTest
public class SpringAiRetryAutoConfigurationRetryTemplateTest {

	private SpringAiRetryAutoConfiguration retryAutoConfiguration;

	private SpringAiRetryProperties mockProperties;

	@BeforeEach
	public void setUp() {
		retryAutoConfiguration = new SpringAiRetryAutoConfiguration();
		mockProperties = Mockito.mock(SpringAiRetryProperties.class);
	}

	@Test
	@Tag("valid")
	public void verifyRetryTemplateConfigurationWithValidProperties() {
		// Arrange
		when(mockProperties.getMaxAttempts()).thenReturn(5);
		Backoff mockBackoff = Mockito.mock(Backoff.class);
		when(mockBackoff.getInitialInterval()).thenReturn(1000L);
		when(mockBackoff.getMultiplier()).thenReturn(2.0);
		when(mockBackoff.getMaxInterval()).thenReturn(10000L);
		when(mockProperties.getBackoff()).thenReturn(mockBackoff);
		// Act
		RetryTemplate retryTemplate = retryAutoConfiguration.retryTemplate(mockProperties);
		// Assert
		assertEquals(5, retryTemplate.getRetryPolicy().getMaxAttempts(), "Max attempts should be 5");
		assertEquals(1000L, retryTemplate.getBackOffPolicy().getInitialInterval(), "Initial interval should be 1000");
		assertEquals(2.0, retryTemplate.getBackOffPolicy().getMultiplier(), "Multiplier should be 2.0");
		assertEquals(10000L, retryTemplate.getBackOffPolicy().getMaxInterval(), "Max interval should be 10000");
	}

}