/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test spring_ai_clone using AI Type AWS Bedrock Runtime AI and AI Model eu.anthropic.claude-sonnet-4-20250514-v1:0

ROOST_METHOD_HASH=doExpression_7373dbacf8
ROOST_METHOD_SIG_HASH=doExpression_f053663651

Scenario 1: Handle NIN Expression Type with Valid Left and Right Operands

Details:
  TestName: ninExpressionTypeConvertsToNotInExpression
  Description: This test verifies that when an expression with type NIN (NOT IN) is processed, the method correctly transforms it into a NOT expression containing an IN expression. The test ensures that the NIN operation is properly converted by calling doNot with a restructured expression.

Execution:
  Arrange: Create a mock Neo4jVectorFilterExpressionConverter instance, prepare a StringBuilder context, create left and right operands (Key and Value), and construct an Expression with ExpressionType.NIN.
  Act: Invoke the doExpression method with the NIN expression and the StringBuilder context.
  Assert: Verify that the doNot method was called with the correct restructured expression (NOT type containing an IN expression), and confirm the context StringBuilder contains the expected NOT prefix.

Validation:
  This assertion verifies that the special handling of NIN expressions is working correctly. The test is significant because NIN expressions need to be transformed into "NOT (left IN right)" format rather than direct processing, ensuring proper Neo4j query syntax generation.

Scenario 2: Handle AND Expression Type with Valid Operands

Details:
  TestName: andExpressionTypeAppendsCorrectOperationSymbol
  Description: This test validates that when an expression with type AND is processed, the method correctly converts the left operand, appends the AND operation symbol, and converts the right operand in the proper sequence.

Execution:
  Arrange: Create a Neo4jVectorFilterExpressionConverter instance, prepare a StringBuilder context, create left and right operands, and construct an Expression with ExpressionType.AND.
  Act: Invoke the doExpression method with the AND expression and the StringBuilder context.
  Assert: Verify that convertOperand was called for both left and right operands, and confirm that the context StringBuilder contains the " AND " symbol between the operands.

Validation:
  This assertion ensures that logical AND operations are properly formatted in the generated Neo4j query. The test is important for validating that compound filter expressions are correctly structured with proper spacing and operator placement.

Scenario 3: Handle OR Expression Type with Valid Operands

Details:
  TestName: orExpressionTypeAppendsCorrectOperationSymbol
  Description: This test ensures that when an expression with type OR is processed, the method correctly processes both operands and inserts the OR operation symbol with proper formatting.

Execution:
  Arrange: Create a Neo4jVectorFilterExpressionConverter instance, prepare a StringBuilder context, create left and right operands, and construct an Expression with ExpressionType.OR.
  Act: Invoke the doExpression method with the OR expression and the StringBuilder context.
  Assert: Verify that both operands are processed via convertOperand calls and that the context StringBuilder contains the " OR " symbol with correct spacing.

Validation:
  This assertion validates that logical OR operations are properly handled and formatted. The test is crucial for ensuring that alternative filter conditions are correctly represented in the Neo4j query syntax.

Scenario 4: Handle EQ Expression Type with Valid Operands

Details:
  TestName: eqExpressionTypeAppendsEqualityOperator
  Description: This test verifies that when an expression with type EQ (equals) is processed, the method correctly formats the equality comparison with the appropriate operator symbol.

Execution:
  Arrange: Create a Neo4jVectorFilterExpressionConverter instance, prepare a StringBuilder context, create left and right operands, and construct an Expression with ExpressionType.EQ.
  Act: Invoke the doExpression method with the EQ expression and the StringBuilder context.
  Assert: Verify that convertOperand is called for both operands and that the context StringBuilder contains the " = " operator symbol.

Validation:
  This assertion confirms that equality comparisons are properly formatted in Neo4j query syntax. The test is essential for validating that exact match filter conditions are correctly represented.

Scenario 5: Handle NE Expression Type with Valid Operands

Details:
  TestName: neExpressionTypeAppendsNotEqualOperator
  Description: This test ensures that when an expression with type NE (not equals) is processed, the method correctly formats the inequality comparison with the Neo4j-specific not equal operator.

Execution:
  Arrange: Create a Neo4jVectorFilterExpressionConverter instance, prepare a StringBuilder context, create left and right operands, and construct an Expression with ExpressionType.NE.
  Act: Invoke the doExpression method with the NE expression and the StringBuilder context.
  Assert: Verify that both operands are processed and that the context StringBuilder contains the " <> " operator symbol specific to Neo4j.

Validation:
  This assertion validates that inequality comparisons use the correct Neo4j operator syntax. The test is important for ensuring that exclusion filter conditions are properly represented using Neo4j's specific not-equal operator.

Scenario 6: Handle LT Expression Type with Valid Operands

Details:
  TestName: ltExpressionTypeAppendsLessThanOperator
  Description: This test validates that when an expression with type LT (less than) is processed, the method correctly formats the comparison with the less than operator.

Execution:
  Arrange: Create a Neo4jVectorFilterExpressionConverter instance, prepare a StringBuilder context, create left and right operands, and construct an Expression with ExpressionType.LT.
  Act: Invoke the doExpression method with the LT expression and the StringBuilder context.
  Assert: Verify that convertOperand is called for both operands and that the context StringBuilder contains the " < " operator symbol.

Validation:
  This assertion ensures that less than comparisons are properly formatted. The test is significant for validating that range-based filter conditions with lower bounds are correctly represented.

Scenario 7: Handle LTE Expression Type with Valid Operands

Details:
  TestName: lteExpressionTypeAppendsLessThanOrEqualOperator
  Description: This test ensures that when an expression with type LTE (less than or equal) is processed, the method correctly formats the comparison with the appropriate operator symbol.

Execution:
  Arrange: Create a Neo4jVectorFilterExpressionConverter instance, prepare a StringBuilder context, create left and right operands, and construct an Expression with ExpressionType.LTE.
  Act: Invoke the doExpression method with the LTE expression and the StringBuilder context.
  Assert: Verify that both operands are processed via convertOperand calls and that the context StringBuilder contains the " <= " operator symbol.

Validation:
  This assertion validates that less than or equal comparisons are properly formatted. The test is important for ensuring that inclusive lower bound filter conditions are correctly represented.

Scenario 8: Handle GT Expression Type with Valid Operands

Details:
  TestName: gtExpressionTypeAppendsGreaterThanOperator
  Description: This test verifies that when an expression with type GT (greater than) is processed, the method correctly formats the comparison with the greater than operator.

Execution:
  Arrange: Create a Neo4jVectorFilterExpressionConverter instance, prepare a StringBuilder context, create left and right operands, and construct an Expression with ExpressionType.GT.
  Act: Invoke the doExpression method with the GT expression and the StringBuilder context.
  Assert: Verify that convertOperand is called for both operands and that the context StringBuilder contains the " > " operator symbol.

Validation:
  This assertion ensures that greater than comparisons are properly formatted. The test is essential for validating that range-based filter conditions with upper bounds are correctly represented.

Scenario 9: Handle GTE Expression Type with Valid Operands

Details:
  TestName: gteExpressionTypeAppendsGreaterThanOrEqualOperator
  Description: This test ensures that when an expression with type GTE (greater than or equal) is processed, the method correctly formats the comparison with the appropriate operator symbol.

Execution:
  Arrange: Create a Neo4jVectorFilterExpressionConverter instance, prepare a StringBuilder context, create left and right operands, and construct an Expression with ExpressionType.GTE.
  Act: Invoke the doExpression method with the GTE expression and the StringBuilder context.
  Assert: Verify that both operands are processed and that the context StringBuilder contains the " >= " operator symbol.

Validation:
  This assertion validates that greater than or equal comparisons are properly formatted. The test is important for ensuring that inclusive upper bound filter conditions are correctly represented.

Scenario 10: Handle IN Expression Type with Valid Operands

Details:
  TestName: inExpressionTypeAppendsInOperator
  Description: This test validates that when an expression with type IN is processed, the method correctly formats the membership test with the IN operator symbol.

Execution:
  Arrange: Create a Neo4jVectorFilterExpressionConverter instance, prepare a StringBuilder context, create left and right operands (where right operand represents a collection), and construct an Expression with ExpressionType.IN.
  Act: Invoke the doExpression method with the IN expression and the StringBuilder context.
  Assert: Verify that convertOperand is called for both operands and that the context StringBuilder contains the " IN " operator symbol.

Validation:
  This assertion ensures that membership tests are properly formatted using Neo4j's IN operator. The test is significant for validating that collection-based filter conditions are correctly represented.

Scenario 11: Handle Expression with Null Left Operand

Details:
  TestName: expressionWithNullLeftOperandHandledGracefully
  Description: This test verifies that when an expression contains a null left operand, the method handles the situation gracefully without throwing unexpected exceptions during operand conversion.

Execution:
  Arrange: Create a Neo4jVectorFilterExpressionConverter instance, prepare a StringBuilder context, create a valid right operand, and construct an Expression with ExpressionType.EQ and null left operand.
  Act: Invoke the doExpression method with the expression containing null left operand and the StringBuilder context.
  Assert: Verify that the method completes execution and that convertOperand handles the null left operand appropriately according to the parent class behavior.

Validation:
  This assertion ensures that null operand scenarios are handled gracefully. The test is important for validating robustness when dealing with incomplete or malformed filter expressions.

Scenario 12: Handle Expression with Null Right Operand

Details:
  TestName: expressionWithNullRightOperandHandledGracefully
  Description: This test ensures that when an expression contains a null right operand, the method processes the left operand and handles the null right operand without causing system failures.

Execution:
  Arrange: Create a Neo4jVectorFilterExpressionConverter instance, prepare a StringBuilder context, create a valid left operand, and construct an Expression with ExpressionType.EQ and null right operand.
  Act: Invoke the doExpression method with the expression containing null right operand and the StringBuilder context.
  Assert: Verify that the method processes the left operand via convertOperand and handles the null right operand appropriately.

Validation:
  This assertion validates that the method maintains stability when encountering null right operands. The test is crucial for ensuring system reliability when processing potentially incomplete filter expressions.

Scenario 13: Handle Expression with Both Null Operands

Details:
  TestName: expressionWithBothNullOperandsHandledGracefully
  Description: This test verifies that when an expression contains both null left and right operands, the method handles the situation without causing system crashes or unexpected behavior.

Execution:
  Arrange: Create a Neo4jVectorFilterExpressionConverter instance, prepare a StringBuilder context, and construct an Expression with ExpressionType.EQ and both null operands.
  Act: Invoke the doExpression method with the expression containing both null operands and the StringBuilder context.
  Assert: Verify that the method completes execution gracefully and that convertOperand calls handle null operands according to parent class implementation.

Validation:
  This assertion ensures complete robustness when dealing with expressions that have no valid operands. The test is essential for validating system stability in edge cases involving malformed filter expressions.

Scenario 14: Verify Operation Symbol Retrieval for NIN Expression in Standard Path

Details:
  TestName: operationSymbolRetrievalForNinExpression
  Description: This test validates that the getOperationSymbol method correctly returns the appropriate symbol for NIN expression type when called during standard expression processing (non-NIN path).

Execution:
  Arrange: Create a Neo4jVectorFilterExpressionConverter instance, prepare a StringBuilder context, create valid operands, and construct an Expression with a non-NIN type that would trigger getOperationSymbol call.
  Act: Invoke the doExpression method and monitor the getOperationSymbol method call for proper symbol retrieval.
  Assert: Verify that getOperationSymbol is called with the correct expression and returns the expected operation symbol for the given expression type.

Validation:
  This assertion ensures that operation symbol retrieval works correctly during standard expression processing. The test is important for validating that the symbol mapping functionality integrates properly with the expression processing flow.

Scenario 15: Verify Context StringBuilder State After Processing

Details:
  TestName: contextStringBuilderStateAfterExpressionProcessing
  Description: This test ensures that after processing any expression type, the StringBuilder context maintains proper state and contains the expected content structure.

Execution:
  Arrange: Create a Neo4jVectorFilterExpressionConverter instance, prepare an empty StringBuilder context, create valid operands, and construct an Expression with ExpressionType.EQ.
  Act: Invoke the doExpression method with the prepared expression and StringBuilder context.
  Assert: Verify that the StringBuilder context is not null, contains content after processing, and maintains proper structure with operands and operators in correct positions.

Validation:
  This assertion validates that the context building process works correctly and produces properly structured output. The test is significant for ensuring that the generated Neo4j query fragments are well-formed and usable.

*/

// ********RoostGPT********

package org.springframework.ai.vectorstore.neo4j.filter;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.MockedStatic;
import org.mockito.Spy;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.ai.vectorstore.filter.Filter;
import org.springframework.ai.vectorstore.filter.Filter.Expression;
import org.springframework.ai.vectorstore.filter.Filter.Key;
import org.springframework.ai.vectorstore.filter.Filter.Value;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.*;
import org.springframework.ai.vectorstore.filter.Filter.Group;
import org.springframework.ai.vectorstore.filter.converter.AbstractFilterExpressionConverter;

@ExtendWith(MockitoExtension.class)
class Neo4JVectorFilterExpressionConverterDoExpressionTest {

	@Spy
	private Neo4jVectorFilterExpressionConverter converter;

	private StringBuilder context;

	@BeforeEach
	void setUp() {
		context = new StringBuilder();
	}

	@Test
	@Tag("valid")
	void ninExpressionTypeConvertsToNotInExpression() {
		// Arrange
		Key leftOperand = new Key("property");
		Value rightOperand = new Value("value");
		Expression ninExpression = new Expression(Filter.ExpressionType.NIN, leftOperand, rightOperand);

		doNothing().when(converter).doNot(any(Expression.class), any(StringBuilder.class));
		// Act
		converter.doExpression(ninExpression, context);
		// Assert
		ArgumentCaptor<Expression> expressionCaptor = ArgumentCaptor.forClass(Expression.class);
		verify(converter).doNot(expressionCaptor.capture(), eq(context));

		Expression capturedExpression = expressionCaptor.getValue();
		assertEquals(Filter.ExpressionType.NOT, capturedExpression.type());
		assertEquals(Filter.ExpressionType.IN, ((Expression) capturedExpression.left()).type());
		assertEquals(leftOperand, ((Expression) capturedExpression.left()).left());
		assertEquals(rightOperand, ((Expression) capturedExpression.left()).right());
	}

	@Test
	@Tag("valid")
	void andExpressionTypeAppendsCorrectOperationSymbol() {
		// Arrange
		Key leftOperand = new Key("property1");
		Value rightOperand = new Value("value1");
		Expression andExpression = new Expression(Filter.ExpressionType.AND, leftOperand, rightOperand);

		doReturn("left").when(converter).convertOperand(eq(leftOperand), any(StringBuilder.class));
		doReturn("right").when(converter).convertOperand(eq(rightOperand), any(StringBuilder.class));
		doNothing().when(converter).convertOperand(any(), any(StringBuilder.class));
		// Act
		converter.doExpression(andExpression, context);
		// Assert
		verify(converter).convertOperand(leftOperand, context);
		verify(converter).convertOperand(rightOperand, context);
		assertTrue(context.toString().contains(" AND "));
	}

	@Test
	@Tag("valid")
	void orExpressionTypeAppendsCorrectOperationSymbol() {
		// Arrange
		Key leftOperand = new Key("property1");
		Value rightOperand = new Value("value1");
		Expression orExpression = new Expression(Filter.ExpressionType.OR, leftOperand, rightOperand);

		doNothing().when(converter).convertOperand(any(), any(StringBuilder.class));
		// Act
		converter.doExpression(orExpression, context);
		// Assert
		verify(converter).convertOperand(leftOperand, context);
		verify(converter).convertOperand(rightOperand, context);
		assertTrue(context.toString().contains(" OR "));
	}

	@Test
	@Tag("valid")
	void eqExpressionTypeAppendsEqualityOperator() {
		// Arrange
		Key leftOperand = new Key("property");
		Value rightOperand = new Value("value");
		Expression eqExpression = new Expression(Filter.ExpressionType.EQ, leftOperand, rightOperand);

		doNothing().when(converter).convertOperand(any(), any(StringBuilder.class));
		// Act
		converter.doExpression(eqExpression, context);
		// Assert
		verify(converter).convertOperand(leftOperand, context);
		verify(converter).convertOperand(rightOperand, context);
		assertTrue(context.toString().contains(" = "));
	}

	@Test
	@Tag("valid")
	void neExpressionTypeAppendsNotEqualOperator() {
		// Arrange
		Key leftOperand = new Key("property");
		Value rightOperand = new Value("value");
		Expression neExpression = new Expression(Filter.ExpressionType.NE, leftOperand, rightOperand);

		doNothing().when(converter).convertOperand(any(), any(StringBuilder.class));
		// Act
		converter.doExpression(neExpression, context);
		// Assert
		verify(converter).convertOperand(leftOperand, context);
		verify(converter).convertOperand(rightOperand, context);
		assertTrue(context.toString().contains(" <> "));
	}

	@Test
	@Tag("valid")
	void ltExpressionTypeAppendsLessThanOperator() {
		// Arrange
		Key leftOperand = new Key("age");
		Value rightOperand = new Value(25);
		Expression ltExpression = new Expression(Filter.ExpressionType.LT, leftOperand, rightOperand);

		doNothing().when(converter).convertOperand(any(), any(StringBuilder.class));
		// Act
		converter.doExpression(ltExpression, context);
		// Assert
		verify(converter).convertOperand(leftOperand, context);
		verify(converter).convertOperand(rightOperand, context);
		assertTrue(context.toString().contains(" < "));
	}

	@Test
	@Tag("valid")
	void lteExpressionTypeAppendsLessThanOrEqualOperator() {
		// Arrange
		Key leftOperand = new Key("age");
		Value rightOperand = new Value(25);
		Expression lteExpression = new Expression(Filter.ExpressionType.LTE, leftOperand, rightOperand);

		doNothing().when(converter).convertOperand(any(), any(StringBuilder.class));
		// Act
		converter.doExpression(lteExpression, context);
		// Assert
		verify(converter).convertOperand(leftOperand, context);
		verify(converter).convertOperand(rightOperand, context);
		assertTrue(context.toString().contains(" <= "));
	}

	@Test
	@Tag("valid")
	void gtExpressionTypeAppendsGreaterThanOperator() {
		// Arrange
		Key leftOperand = new Key("score");
		Value rightOperand = new Value(100);
		Expression gtExpression = new Expression(Filter.ExpressionType.GT, leftOperand, rightOperand);

		doNothing().when(converter).convertOperand(any(), any(StringBuilder.class));
		// Act
		converter.doExpression(gtExpression, context);
		// Assert
		verify(converter).convertOperand(leftOperand, context);
		verify(converter).convertOperand(rightOperand, context);
		assertTrue(context.toString().contains(" > "));
	}

	@Test
	@Tag("valid")
	void gteExpressionTypeAppendsGreaterThanOrEqualOperator() {
		// Arrange
		Key leftOperand = new Key("score");
		Value rightOperand = new Value(100);
		Expression gteExpression = new Expression(Filter.ExpressionType.GTE, leftOperand, rightOperand);

		doNothing().when(converter).convertOperand(any(), any(StringBuilder.class));
		// Act
		converter.doExpression(gteExpression, context);
		// Assert
		verify(converter).convertOperand(leftOperand, context);
		verify(converter).convertOperand(rightOperand, context);
		assertTrue(context.toString().contains(" >= "));
	}

	@Test
	@Tag("valid")
	void inExpressionTypeAppendsInOperator() {
		// Arrange
		Key leftOperand = new Key("category");
		Value rightOperand = new Value(new String[] { "electronics", "books" });
		Expression inExpression = new Expression(Filter.ExpressionType.IN, leftOperand, rightOperand);

		doNothing().when(converter).convertOperand(any(), any(StringBuilder.class));
		// Act
		converter.doExpression(inExpression, context);
		// Assert
		verify(converter).convertOperand(leftOperand, context);
		verify(converter).convertOperand(rightOperand, context);
		assertTrue(context.toString().contains(" IN "));
	}

	@Test
	@Tag("boundary")
	void expressionWithNullLeftOperandHandledGracefully() {
		// Arrange
		Value rightOperand = new Value("value");
		Expression expression = new Expression(Filter.ExpressionType.EQ, null, rightOperand);

		doNothing().when(converter).convertOperand(any(), any(StringBuilder.class));
		// Act & Assert
		assertDoesNotThrow(() -> converter.doExpression(expression, context));
		verify(converter).convertOperand(null, context);
		verify(converter).convertOperand(rightOperand, context);
	}

	@Test
	@Tag("boundary")
	void expressionWithNullRightOperandHandledGracefully() {
		// Arrange
		Key leftOperand = new Key("property");
		Expression expression = new Expression(Filter.ExpressionType.EQ, leftOperand, null);

		doNothing().when(converter).convertOperand(any(), any(StringBuilder.class));
		// Act & Assert
		assertDoesNotThrow(() -> converter.doExpression(expression, context));
		verify(converter).convertOperand(leftOperand, context);
		verify(converter).convertOperand(null, context);
	}

	@Test
	@Tag("boundary")
	void expressionWithBothNullOperandsHandledGracefully() {
		// Arrange
		Expression expression = new Expression(Filter.ExpressionType.EQ, null, null);

		doNothing().when(converter).convertOperand(any(), any(StringBuilder.class));
		// Act & Assert
		assertDoesNotThrow(() -> converter.doExpression(expression, context));
		verify(converter).convertOperand(isNull(), eq(context));
		verify(converter, times(2)).convertOperand(isNull(), eq(context));
	}

	@Test
	@Tag("valid")
	void operationSymbolRetrievalForNinExpression() {
		// Arrange
		Key leftOperand = new Key("property");
		Value rightOperand = new Value("value");
		Expression eqExpression = new Expression(Filter.ExpressionType.EQ, leftOperand, rightOperand);

		doNothing().when(converter).convertOperand(any(), any(StringBuilder.class));
		// Act
		converter.doExpression(eqExpression, context);
		// Assert
		verify(converter).convertOperand(leftOperand, context);
		verify(converter).convertOperand(rightOperand, context);
		assertTrue(context.toString().contains(" = "));
	}

	@Test
	@Tag("valid")
	void contextStringBuilderStateAfterExpressionProcessing() {
		// Arrange
		Key leftOperand = new Key("name");
		Value rightOperand = new Value("test");
		Expression eqExpression = new Expression(Filter.ExpressionType.EQ, leftOperand, rightOperand);

		doAnswer(invocation -> {
			StringBuilder sb = invocation.getArgument(1);
			sb.append("operand");
			return null;
		}).when(converter).convertOperand(any(), any(StringBuilder.class));
		// Act
		converter.doExpression(eqExpression, context);
		// Assert
		assertNotNull(context);
		assertTrue(context.length() > 0);
		String result = context.toString();
		assertTrue(result.contains("operand"));
		assertTrue(result.contains(" = "));
		assertTrue(result.endsWith("operand"));
	}

}