/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test spring_ai using AI Type AWS Bedrock Runtime AI and AI Model eu.anthropic.claude-sonnet-4-20250514-v1:0

ROOST_METHOD_HASH=doExpression_7373dbacf8
ROOST_METHOD_SIG_HASH=doExpression_f053663651

Scenario 1: Expression with NIN type triggers NOT-IN conversion

Details:
  TestName: expressionWithNinTypeTriggersNotInConversion
  Description: This test verifies that when an Expression has ExpressionType.NIN, the method correctly delegates to the doNot method with a transformed Expression that wraps an IN expression inside a NOT expression. This ensures proper handling of "not in" operations by converting them to "not (in)" operations.

Execution:
  Arrange: Create a mock Expression with type NIN, mock left and right operands, create a StringBuilder context, and set up spy on the converter to verify doNot method invocation.
  Act: Call the doExpression method with the NIN expression and context StringBuilder.
  Assert: Verify that doNot method was called exactly once with the correct transformed Expression (NOT wrapping IN) and the same context StringBuilder.

Validation:
  The assertion verifies that NIN expressions are properly transformed into NOT(IN) expressions before being processed. This is crucial for maintaining consistency in the filter expression conversion logic, as it standardizes the handling of negation operations by always using the NOT wrapper approach rather than having separate logic for NIN.

Scenario 2: Expression with EQ type processes operands and symbol directly

Details:
  TestName: expressionWithEqTypeProcessesOperandsAndSymbolDirectly
  Description: This test ensures that when an Expression has a type other than NIN (such as EQ), the method follows the standard conversion path by processing the left operand, appending the operation symbol, and then processing the right operand in sequence.

Execution:
  Arrange: Create an Expression with ExpressionType.EQ, mock left and right operands, create a StringBuilder context, and set up mocks for convertOperand and getOperationSymbol methods.
  Act: Invoke the doExpression method with the EQ expression and context StringBuilder.
  Assert: Verify that convertOperand was called twice (once for left, once for right operand), getOperationSymbol was called once with the expression, and the context StringBuilder contains the expected operation symbol.

Validation:
  This assertion confirms that non-NIN expressions follow the standard three-step conversion process. This is essential for ensuring that equality and other comparison operations are properly formatted in the output filter expression, maintaining the correct syntax and operand order.

Scenario 3: Expression with GT type appends correct operation symbol

Details:
  TestName: expressionWithGtTypeAppendsCorrectOperationSymbol
  Description: This test validates that when processing a Greater Than (GT) expression, the method correctly retrieves and appends the appropriate operation symbol between the left and right operands, ensuring proper operator precedence and formatting.

Execution:
  Arrange: Create an Expression with ExpressionType.GT, mock Key and Value operands, create a StringBuilder context, and configure the getOperationSymbol method to return the GT symbol.
  Act: Call the doExpression method with the GT expression and context.
  Assert: Verify that the context StringBuilder contains the operands and the GT operation symbol in the correct order, and that all method calls occurred in the expected sequence.

Validation:
  The assertion ensures that comparison operators are correctly positioned between operands in the generated filter expression. This is vital for producing syntactically correct and semantically meaningful filter queries that can be properly interpreted by the downstream Neo4j database system.

Scenario 4: Expression with complex nested operands processes correctly

Details:
  TestName: expressionWithComplexNestedOperandsProcessesCorrectly
  Description: This test examines the method's ability to handle expressions where the left and right operands are themselves complex objects (such as nested expressions or composite keys), ensuring that the convertOperand method is called appropriately for complex data structures.

Execution:
  Arrange: Create an Expression with ExpressionType.LT, create complex nested operands (Group or nested Expression objects), create a StringBuilder context, and mock the convertOperand method to handle complex objects.
  Act: Execute the doExpression method with the expression containing complex operands.
  Assert: Verify that convertOperand was invoked for both complex operands, the operation symbol was appended, and no exceptions were thrown during processing.

Validation:
  This assertion validates the method's robustness in handling sophisticated filter expressions with nested structures. This capability is crucial for supporting advanced filtering scenarios where users need to combine multiple conditions or work with hierarchical data structures in their vector store queries.

Scenario 5: NIN expression with null operands handles gracefully

Details:
  TestName: ninExpressionWithNullOperandsHandlesGracefully
  Description: This test verifies the method's behavior when processing a NIN expression that contains null left or right operands, ensuring that the transformation to NOT(IN) structure is still attempted and that the doNot method receives the properly constructed Expression despite null operands.

Execution:
  Arrange: Create an Expression with ExpressionType.NIN where either left or right operand is null, create a StringBuilder context, and set up verification for the doNot method call.
  Act: Invoke the doExpression method with the NIN expression containing null operands.
  Assert: Verify that doNot method was called with the transformed Expression structure and that no NullPointerException was thrown during the transformation process.

Validation:
  The assertion ensures that the method maintains structural integrity even when dealing with incomplete expression data. This robustness is important for preventing system crashes and providing predictable behavior when processing malformed or incomplete filter expressions from user input.

Scenario 6: Expression with IN type processes through standard path

Details:
  TestName: expressionWithInTypeProcessesThroughStandardPath
  Description: This test confirms that when an Expression has ExpressionType.IN (not NIN), it follows the standard processing path rather than the special NIN transformation, ensuring that IN operations are handled as regular binary operations.

Execution:
  Arrange: Create an Expression with ExpressionType.IN, create appropriate left and right operands, create a StringBuilder context, and mock the supporting methods.
  Act: Call the doExpression method with the IN expression and context.
  Assert: Verify that the doNot method was not called, convertOperand was called for both operands, and getOperationSymbol was called with the IN expression.

Validation:
  This assertion distinguishes between IN and NIN operations, ensuring that only NIN expressions trigger the special transformation logic. This differentiation is critical for maintaining correct semantics where IN operations should be processed directly while NIN operations require negation transformation.

Scenario 7: Multiple sequential expressions modify context correctly

Details:
  TestName: multipleSequentialExpressionsModifyContextCorrectly
  Description: This test evaluates the method's behavior when called multiple times with different expressions using the same StringBuilder context, ensuring that each expression properly appends to the context without interfering with previous results.

Execution:
  Arrange: Create multiple Expression objects with different types (EQ, GT, LT), create a single StringBuilder context, and configure appropriate mock responses for supporting methods.
  Act: Call the doExpression method multiple times with different expressions and the same context StringBuilder.
  Assert: Verify that the context StringBuilder accumulates content from all expressions in the correct order and that each expression's processing is independent of others.

Validation:
  The assertion confirms that the method maintains stateless behavior and properly accumulates results in the shared context. This is essential for building complex filter expressions that combine multiple conditions, ensuring that the final output represents the complete logical expression structure.

Scenario 8: Empty StringBuilder context receives expression content

Details:
  TestName: emptyStringBuilderContextReceivesExpressionContent
  Description: This test verifies that when starting with an empty StringBuilder context, the method properly populates it with the expression components (left operand, operation symbol, right operand) in the correct sequence and format.

Execution:
  Arrange: Create an Expression with ExpressionType.EQ, create a new empty StringBuilder context, and configure mocks to return specific string values for operands and operation symbol.
  Act: Execute the doExpression method with the expression and empty context.
  Assert: Verify that the context StringBuilder transitions from empty to containing the expected expression format, and that the content matches the expected pattern for the given expression type.

Validation:
  This assertion ensures that the method correctly initializes and populates the output context from a clean state. This functionality is fundamental for the first expression in a filter chain and validates that the method can properly bootstrap the expression building process.

*/

// ********RoostGPT********

package org.springframework.ai.vectorstore.neo4j.filter;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.Spy;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.ai.vectorstore.filter.Filter;
import org.springframework.ai.vectorstore.filter.Filter.Expression;
import org.springframework.ai.vectorstore.filter.Filter.Group;
import org.springframework.ai.vectorstore.filter.Filter.Key;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.*;
import org.springframework.ai.vectorstore.filter.converter.AbstractFilterExpressionConverter;

@ExtendWith(MockitoExtension.class)
public class Neo4JVectorFilterExpressionConverterDoExpressionTest {

	@Spy
	private Neo4jVectorFilterExpressionConverter converter;

	@Mock
	private Filter.Operand leftOperand;

	@Mock
	private Filter.Operand rightOperand;

	@Mock
	private Key keyOperand;

	@Mock
	private Filter.Value valueOperand;

	@Mock
	private Group groupOperand;

	private StringBuilder context;

	@BeforeEach
	void setUp() {
		context = new StringBuilder();
		doNothing().when(converter).convertOperand(any(), any());
		when(converter.getOperationSymbol(any())).thenReturn(" = ");
		doNothing().when(converter).doNot(any(), any());
	}

	@Test
	@Tag("valid")
	void expressionWithNinTypeTriggersNotInConversion() {
		// Arrange
		Expression ninExpression = new Expression(Filter.ExpressionType.NIN, leftOperand, rightOperand);
		// Act
		converter.doExpression(ninExpression, context);
		// Assert
		verify(converter, times(1)).doNot(any(Expression.class), eq(context));
		verify(converter, never()).convertOperand(any(), any());
		verify(converter, never()).getOperationSymbol(any());
	}

	@Test
	@Tag("valid")
	void expressionWithEqTypeProcessesOperandsAndSymbolDirectly() {
		// Arrange
		Expression eqExpression = new Expression(Filter.ExpressionType.EQ, leftOperand, rightOperand);
		when(converter.getOperationSymbol(eqExpression)).thenReturn(" = ");
		// Act
		converter.doExpression(eqExpression, context);
		// Assert
		verify(converter, times(1)).convertOperand(leftOperand, context);
		verify(converter, times(1)).convertOperand(rightOperand, context);
		verify(converter, times(1)).getOperationSymbol(eqExpression);
		verify(converter, never()).doNot(any(), any());
		assertEquals(" = ", context.toString());
	}

	@Test
	@Tag("valid")
	void expressionWithGtTypeAppendsCorrectOperationSymbol() {
		// Arrange
		Expression gtExpression = new Expression(Filter.ExpressionType.GT, keyOperand, valueOperand);
		when(converter.getOperationSymbol(gtExpression)).thenReturn(" > ");
		// Act
		converter.doExpression(gtExpression, context);
		// Assert
		verify(converter, times(1)).convertOperand(keyOperand, context);
		verify(converter, times(1)).convertOperand(valueOperand, context);
		verify(converter, times(1)).getOperationSymbol(gtExpression);
		assertEquals(" > ", context.toString());
	}

	@Test
	@Tag("valid")
	void expressionWithComplexNestedOperandsProcessesCorrectly() {
		// Arrange
		Expression nestedExpression = new Expression(Filter.ExpressionType.LT, leftOperand, rightOperand);
		Expression ltExpression = new Expression(Filter.ExpressionType.LT, groupOperand, nestedExpression);
		when(converter.getOperationSymbol(ltExpression)).thenReturn(" < ");
		// Act
		assertDoesNotThrow(() -> converter.doExpression(ltExpression, context));
		// Assert
		verify(converter, times(1)).convertOperand(groupOperand, context);
		verify(converter, times(1)).convertOperand(nestedExpression, context);
		verify(converter, times(1)).getOperationSymbol(ltExpression);
		assertEquals(" < ", context.toString());
	}

	@Test
	@Tag("boundary")
	void ninExpressionWithNullOperandsHandlesGracefully() {
		// Arrange
		Expression ninExpression = new Expression(Filter.ExpressionType.NIN, null, rightOperand);
		// Act
		assertDoesNotThrow(() -> converter.doExpression(ninExpression, context));
		// Assert
		verify(converter, times(1)).doNot(any(Expression.class), eq(context));
		verify(converter, never()).convertOperand(any(), any());
		verify(converter, never()).getOperationSymbol(any());
	}

	@Test
	@Tag("valid")
	void expressionWithInTypeProcessesThroughStandardPath() {
		// Arrange
		Expression inExpression = new Expression(Filter.ExpressionType.IN, leftOperand, rightOperand);
		when(converter.getOperationSymbol(inExpression)).thenReturn(" IN ");
		// Act
		converter.doExpression(inExpression, context);
		// Assert
		verify(converter, never()).doNot(any(), any());
		verify(converter, times(1)).convertOperand(leftOperand, context);
		verify(converter, times(1)).convertOperand(rightOperand, context);
		verify(converter, times(1)).getOperationSymbol(inExpression);
		assertEquals(" IN ", context.toString());
	}

	@Test
	@Tag("integration")
	void multipleSequentialExpressionsModifyContextCorrectly() {
		// Arrange
		Expression eqExpression = new Expression(Filter.ExpressionType.EQ, leftOperand, rightOperand);
		Expression gtExpression = new Expression(Filter.ExpressionType.GT, keyOperand, valueOperand);
		Expression ltExpression = new Expression(Filter.ExpressionType.LT, groupOperand, leftOperand);
		when(converter.getOperationSymbol(eqExpression)).thenReturn(" = ");
		when(converter.getOperationSymbol(gtExpression)).thenReturn(" > ");
		when(converter.getOperationSymbol(ltExpression)).thenReturn(" < ");
		// Act
		converter.doExpression(eqExpression, context);
		converter.doExpression(gtExpression, context);
		converter.doExpression(ltExpression, context);
		// Assert
		verify(converter, times(6)).convertOperand(any(), eq(context));
		verify(converter, times(3)).getOperationSymbol(any());
		assertEquals(" =  >  < ", context.toString());
	}

	@Test
	@Tag("valid")
	void emptyStringBuilderContextReceivesExpressionContent() {
		// Arrange
		Expression eqExpression = new Expression(Filter.ExpressionType.EQ, leftOperand, rightOperand);
		when(converter.getOperationSymbol(eqExpression)).thenReturn(" = ");
		assertTrue(context.length() == 0);
		// Act
		converter.doExpression(eqExpression, context);
		// Assert
		verify(converter, times(1)).convertOperand(leftOperand, context);
		verify(converter, times(1)).convertOperand(rightOperand, context);
		verify(converter, times(1)).getOperationSymbol(eqExpression);
		assertEquals(" = ", context.toString());
		assertTrue(context.length() > 0);
	}

	@Test
	@Tag("boundary")
	void ninExpressionWithBothNullOperandsHandlesGracefully() {
		// Arrange
		Expression ninExpression = new Expression(Filter.ExpressionType.NIN, null, null);
		// Act
		assertDoesNotThrow(() -> converter.doExpression(ninExpression, context));
		// Assert
		verify(converter, times(1)).doNot(any(Expression.class), eq(context));
		verify(converter, never()).convertOperand(any(), any());
		verify(converter, never()).getOperationSymbol(any());
	}

	@Test
	@Tag("valid")
	void expressionWithNeTypeProcessesThroughStandardPath() {
		// Arrange
		Expression neExpression = new Expression(Filter.ExpressionType.NE, leftOperand, rightOperand);
		when(converter.getOperationSymbol(neExpression)).thenReturn(" <> ");
		// Act
		converter.doExpression(neExpression, context);
		// Assert
		verify(converter, never()).doNot(any(), any());
		verify(converter, times(1)).convertOperand(leftOperand, context);
		verify(converter, times(1)).convertOperand(rightOperand, context);
		verify(converter, times(1)).getOperationSymbol(neExpression);
		assertEquals(" <> ", context.toString());
	}

	@Test
	@Tag("valid")
	void expressionWithGteTypeProcessesThroughStandardPath() {
		// Arrange
		Expression gteExpression = new Expression(Filter.ExpressionType.GTE, keyOperand, valueOperand);
		when(converter.getOperationSymbol(gteExpression)).thenReturn(" >= ");
		// Act
		converter.doExpression(gteExpression, context);
		// Assert
		verify(converter, never()).doNot(any(), any());
		verify(converter, times(1)).convertOperand(keyOperand, context);
		verify(converter, times(1)).convertOperand(valueOperand, context);
		verify(converter, times(1)).getOperationSymbol(gteExpression);
		assertEquals(" >= ", context.toString());
	}

	@Test
	@Tag("valid")
	void expressionWithLteTypeProcessesThroughStandardPath() {
		// Arrange
		Expression lteExpression = new Expression(Filter.ExpressionType.LTE, leftOperand, rightOperand);
		when(converter.getOperationSymbol(lteExpression)).thenReturn(" <= ");
		// Act
		converter.doExpression(lteExpression, context);
		// Assert
		verify(converter, never()).doNot(any(), any());
		verify(converter, times(1)).convertOperand(leftOperand, context);
		verify(converter, times(1)).convertOperand(rightOperand, context);
		verify(converter, times(1)).getOperationSymbol(lteExpression);
		assertEquals(" <= ", context.toString());
	}

}