/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test spring_ai using AI Type AWS Bedrock Runtime AI and AI Model eu.anthropic.claude-sonnet-4-20250514-v1:0
ROOST_METHOD_HASH=doExpression_7373dbacf8
ROOST_METHOD_SIG_HASH=doExpression_f053663651
Scenario 1: Expression with NIN type triggers NOT-IN conversion
Details:
  TestName: expressionWithNinTypeTriggersNotInConversion
  Description: This test verifies that when an Expression has ExpressionType.NIN, the method correctly delegates to the doNot method with a transformed Expression that wraps an IN expression inside a NOT expression. This ensures proper handling of "not in" operations by converting them to "not (in)" operations.
Execution:
  Arrange: Create a mock Expression with type NIN, mock left and right operands, create a StringBuilder context, and set up spy on the converter to verify doNot method invocation.
  Act: Call the doExpression method with the NIN expression and context StringBuilder.
  Assert: Verify that doNot method was called exactly once with the correct transformed Expression (NOT wrapping IN) and the same context StringBuilder.
Validation:
  The assertion verifies that NIN expressions are properly transformed into NOT(IN) expressions before being processed. This is crucial for maintaining consistency in the filter expression conversion logic, as it standardizes the handling of negation operations by always using the NOT wrapper approach rather than having separate logic for NIN.
Scenario 2: Expression with EQ type processes operands and symbol directly
Details:
  TestName: expressionWithEqTypeProcessesOperandsAndSymbolDirectly
  Description: This test ensures that when an Expression has a type other than NIN (such as EQ), the method follows the standard conversion path by processing the left operand, appending the operation symbol, and then processing the right operand in sequence.
Execution:
  Arrange: Create an Expression with ExpressionType.EQ, mock left and right operands, create a StringBuilder context, and set up mocks for convertOperand and getOperationSymbol methods.
  Act: Invoke the doExpression method with the EQ expression and context StringBuilder.
  Assert: Verify that convertOperand was called twice (once for left, once for right operand), getOperationSymbol was called once with the expression, and the context StringBuilder contains the expected operation symbol.
Validation:
  This assertion confirms that non-NIN expressions follow the standard three-step conversion process. This is essential for ensuring that equality and other comparison operations are properly formatted in the output filter expression, maintaining the correct syntax and operand order.
Scenario 3: Expression with GT type appends correct operation symbol
Details:
  TestName: expressionWithGtTypeAppendsCorrectOperationSymbol
  Description: This test validates that when processing a Greater Than (GT) expression, the method correctly retrieves and appends the appropriate operation symbol between the left and right operands, ensuring proper operator precedence and formatting.
Execution:
  Arrange: Create an Expression with ExpressionType.GT, mock Key and Value operands, create a StringBuilder context, and configure the getOperationSymbol method to return the GT symbol.
  Act: Call the doExpression method with the GT expression and context.
  Assert: Verify that the context StringBuilder contains the operands and the GT operation symbol in the correct order, and that all method calls occurred in the expected sequence.
Validation:
  The assertion ensures that comparison operators are correctly positioned between operands in the generated filter expression. This is vital for producing syntactically correct and semantically meaningful filter queries that can be properly interpreted by the downstream Neo4j database system.
Scenario 4: Expression with complex nested operands processes correctly
Details:
  TestName: expressionWithComplexNestedOperandsProcessesCorrectly
  Description: This test examines the method's ability to handle expressions where the left and right operands are themselves complex objects (such as nested expressions or composite keys), ensuring that the convertOperand method is called appropriately for complex data structures.
Execution:
  Arrange: Create an Expression with ExpressionType.LT, create complex nested operands (Group or nested Expression objects), create a StringBuilder context, and mock the convertOperand method to handle complex objects.
  Act: Execute the doExpression method with the expression containing complex operands.
  Assert: Verify that convertOperand was invoked for both complex operands, the operation symbol was appended, and no exceptions were thrown during processing.
Validation:
  This assertion validates the method's robustness in handling sophisticated filter expressions with nested structures. This capability is crucial for supporting advanced filtering scenarios where users need to combine multiple conditions or work with hierarchical data structures in their vector store queries.
Scenario 5: NIN expression with null operands handles gracefully
Details:
  TestName: ninExpressionWithNullOperandsHandlesGracefully
  Description: This test verifies the method's behavior when processing a NIN expression that contains null left or right operands, ensuring that the transformation to NOT(IN) structure is still attempted and that the doNot method receives the properly constructed Expression despite null operands.
Execution:
  Arrange: Create an Expression with ExpressionType.NIN where either left or right operand is null, create a StringBuilder context, and set up verification for the doNot method call.
  Act: Invoke the doExpression method with the NIN expression containing null operands.
  Assert: Verify that doNot method was called with the transformed Expression structure and that no NullPointerException was thrown during the transformation process.
Validation:
  The assertion ensures that the method maintains structural integrity even when dealing with incomplete expression data. This robustness is important for preventing system crashes and providing predictable behavior when processing malformed or incomplete filter expressions from user input.
Scenario 6: Expression with IN type processes through standard path
Details:
  TestName: expressionWithInTypeProcessesThroughStandardPath
  Description: This test confirms that when an Expression has ExpressionType.IN (not NIN), it follows the standard processing path rather than the special NIN transformation, ensuring that IN operations are handled as regular binary operations.
Execution:
  Arrange: Create an Expression with ExpressionType.IN, create appropriate left and right operands, create a StringBuilder context, and mock the supporting methods.
  Act: Call the doExpression method with the IN expression and context.
  Assert: Verify that the doNot method was not called, convertOperand was called for both operands, and getOperationSymbol was called with the IN expression.
Validation:
  This assertion distinguishes between IN and NIN operations, ensuring that only NIN expressions trigger the special transformation logic. This differentiation is critical for maintaining correct semantics where IN operations should be processed directly while NIN operations require negation transformation.
Scenario 7: Multiple sequential expressions modify context correctly
Details:
  TestName: multipleSequentialExpressionsModifyContextCorrectly
  Description: This test evaluates the method's behavior when called multiple times with different expressions using the same StringBuilder context, ensuring that each expression properly appends to the context without interfering with previous results.
Execution:
  Arrange: Create multiple Expression objects with different types (EQ, GT, LT), create a single StringBuilder context, and configure appropriate mock responses for supporting methods.
  Act: Call the doExpression method multiple times with different expressions and the same context StringBuilder.
  Assert: Verify that the context StringBuilder accumulates content from all expressions in the correct order and that each expression's processing is independent of others.
Validation:
  The assertion confirms that the method maintains stateless behavior and properly accumulates results in the shared context. This is essential for building complex filter expressions that combine multiple conditions, ensuring that the final output represents the complete logical expression structure.
Scenario 8: Empty StringBuilder context receives expression content
Details:
  TestName: emptyStringBuilderContextReceivesExpressionContent
  Description: This test verifies that when starting with an empty StringBuilder context, the method properly populates it with the expression components (left operand, operation symbol, right operand) in the correct sequence and format.
Execution:
  Arrange: Create an Expression with ExpressionType.EQ, create a new empty StringBuilder context, and configure mocks to return specific string values for operands and operation symbol.
  Act: Execute the doExpression method with the expression and empty context.
  Assert: Verify that the context StringBuilder transitions from empty to containing the expected expression format, and that the content matches the expected pattern for the given expression type.
Validation:
  This assertion ensures that the method correctly initializes and populates the output context from a clean state. This functionality is fundamental for the first expression in a filter chain and validates that the method can properly bootstrap the expression building process.
*/
// ********RoostGPT********
package org.springframework.ai.vectorstore.neo4j.filter;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.ai.vectorstore.filter.Filter;
import org.springframework.ai.vectorstore.filter.Filter.Expression;
import org.springframework.ai.vectorstore.filter.Filter.Group;
import org.springframework.ai.vectorstore.filter.Filter.Key;
import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.doNothing;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.spy;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import org.springframework.ai.vectorstore.filter.converter.AbstractFilterExpressionConverter;
import org.junit.jupiter.api.*;

@Tag("org.springframework.ai.vectorstore.neo4j.filter")
@Tag("org.springframework.ai.vectorstore.neo4j.filter.doExpression")
class Neo4JVectorFilterExpressionConverterDoExpressionTest {

	private Neo4jVectorFilterExpressionConverter converter;

	@Mock
	private Filter.Operand leftOperand;

	@Mock
	private Filter.Operand rightOperand;

	@Mock
	private Key keyOperand;

	@Mock
	private Filter.Value valueOperand;

	@Mock
	private Group groupOperand;

	@BeforeEach
	void setUp() {
		MockitoAnnotations.openMocks(this);
		this.converter = spy(new TestableNeo4jVectorFilterExpressionConverter());
	}

	@Test
	@Tag("valid")
	void expressionWithNinTypeTriggersNotInConversion() {
		// Arrange
		Expression ninExpression = new Expression(Filter.ExpressionType.NIN, this.leftOperand, this.rightOperand);
		StringBuilder context = new StringBuilder();
		doNothing().when(this.converter).doNot(any(Expression.class), eq(context));
		// Act
		this.converter.doExpression(ninExpression, context);
		// Assert
		ArgumentCaptor<Expression> expressionCaptor = ArgumentCaptor.forClass(Expression.class);
		verify(this.converter, times(1)).doNot(expressionCaptor.capture(), eq(context));
		Expression capturedExpression = expressionCaptor.getValue();
		assertEquals(Filter.ExpressionType.NOT, capturedExpression.type());
		Expression innerExpression = (Expression) capturedExpression.left();
		assertEquals(Filter.ExpressionType.IN, innerExpression.type());
		assertEquals(this.leftOperand, innerExpression.left());
		assertEquals(this.rightOperand, innerExpression.right());
	}

	@Test
	@Tag("valid")
	void expressionWithEqTypeProcessesOperandsAndSymbolDirectly() {
		// Arrange
		Expression eqExpression = new Expression(Filter.ExpressionType.EQ, this.leftOperand, this.rightOperand);
		StringBuilder context = new StringBuilder();
		doNothing().when(this.converter).convertOperand(any(), any());
		when(this.converter.getOperationSymbol(eqExpression)).thenReturn(" = ");
		// Act
		this.converter.doExpression(eqExpression, context);
		// Assert
		verify(this.converter, times(1)).convertOperand(this.leftOperand, context);
		verify(this.converter, times(1)).convertOperand(this.rightOperand, context);
		verify(this.converter, times(1)).getOperationSymbol(eqExpression);
		assertEquals(" = ", context.toString());
	}

	@Test
	@Tag("valid")
	void expressionWithGtTypeAppendsCorrectOperationSymbol() {
		// Arrange
		Expression gtExpression = new Expression(Filter.ExpressionType.GT, this.keyOperand, this.valueOperand);
		StringBuilder context = new StringBuilder();
		doAnswer(invocation -> {
			StringBuilder sb = invocation.getArgument(1);
			sb.append("key");
			return null;
		}).when(this.converter).convertOperand(eq(this.keyOperand), eq(context));
		doAnswer(invocation -> {
			StringBuilder sb = invocation.getArgument(1);
			sb.append("value");
			return null;
		}).when(this.converter).convertOperand(eq(this.valueOperand), eq(context));
		when(this.converter.getOperationSymbol(gtExpression)).thenReturn(" > ");
		// Act
		this.converter.doExpression(gtExpression, context);
		// Assert
		assertEquals("key > value", context.toString());
		verify(this.converter, times(1)).convertOperand(this.keyOperand, context);
		verify(this.converter, times(1)).getOperationSymbol(gtExpression);
		verify(this.converter, times(1)).convertOperand(this.valueOperand, context);
	}

	@Test
	@Tag("valid")
	void expressionWithComplexNestedOperandsProcessesCorrectly() {
		// Arrange
		Expression ltExpression = new Expression(Filter.ExpressionType.LT, this.groupOperand, this.leftOperand);
		StringBuilder context = new StringBuilder();
		doAnswer(invocation -> {
			StringBuilder sb = invocation.getArgument(1);
			sb.append("(nested_group)");
			return null;
		}).when(this.converter).convertOperand(eq(this.groupOperand), eq(context));
		doAnswer(invocation -> {
			StringBuilder sb = invocation.getArgument(1);
			sb.append("operand");
			return null;
		}).when(this.converter).convertOperand(eq(this.leftOperand), eq(context));
		when(this.converter.getOperationSymbol(ltExpression)).thenReturn(" < ");
		// Act
		assertDoesNotThrow(() -> this.converter.doExpression(ltExpression, context));
		// Assert
		verify(this.converter, times(1)).convertOperand(this.groupOperand, context);
		verify(this.converter, times(1)).convertOperand(this.leftOperand, context);
		verify(this.converter, times(1)).getOperationSymbol(ltExpression);
		assertEquals("(nested_group) < operand", context.toString());
	}

	@Test
	@Tag("boundary")
	void ninExpressionWithNullOperandsHandlesGracefully() {
		// Arrange
		Expression ninExpression = new Expression(Filter.ExpressionType.NIN, null, this.rightOperand);
		StringBuilder context = new StringBuilder();
		doNothing().when(this.converter).doNot(any(Expression.class), eq(context));
		// Act
		assertDoesNotThrow(() -> this.converter.doExpression(ninExpression, context));
		// Assert
		ArgumentCaptor<Expression> expressionCaptor = ArgumentCaptor.forClass(Expression.class);
		verify(this.converter, times(1)).doNot(expressionCaptor.capture(), eq(context));
		Expression capturedExpression = expressionCaptor.getValue();
		assertEquals(Filter.ExpressionType.NOT, capturedExpression.type());
		Expression innerExpression = (Expression) capturedExpression.left();
		assertEquals(Filter.ExpressionType.IN, innerExpression.type());
		assertNull(innerExpression.left());
		assertEquals(this.rightOperand, innerExpression.right());
	}

	@Test
	@Tag("valid")
	void expressionWithInTypeProcessesThroughStandardPath() {
		// Arrange
		Expression inExpression = new Expression(Filter.ExpressionType.IN, this.leftOperand, this.rightOperand);
		StringBuilder context = new StringBuilder();
		doNothing().when(this.converter).convertOperand(any(), any());
		when(this.converter.getOperationSymbol(inExpression)).thenReturn(" IN ");
		// Act
		this.converter.doExpression(inExpression, context);
		// Assert
		verify(this.converter, never()).doNot(any(), any());
		verify(this.converter, times(1)).convertOperand(this.leftOperand, context);
		verify(this.converter, times(1)).convertOperand(this.rightOperand, context);
		verify(this.converter, times(1)).getOperationSymbol(inExpression);
		assertEquals(" IN ", context.toString());
	}

	@Test
	@Tag("integration")
	void multipleSequentialExpressionsModifyContextCorrectly() {
		// Arrange
		Expression eqExpression = new Expression(Filter.ExpressionType.EQ, this.leftOperand, this.rightOperand);
		Expression gtExpression = new Expression(Filter.ExpressionType.GT, this.keyOperand, this.valueOperand);
		Expression ltExpression = new Expression(Filter.ExpressionType.LT, this.leftOperand, this.rightOperand);
		StringBuilder context = new StringBuilder();
		doAnswer(invocation -> {
			StringBuilder sb = invocation.getArgument(1);
			sb.append("left");
			return null;
		}).when(this.converter).convertOperand(eq(this.leftOperand), eq(context));
		doAnswer(invocation -> {
			StringBuilder sb = invocation.getArgument(1);
			sb.append("right");
			return null;
		}).when(this.converter).convertOperand(eq(this.rightOperand), eq(context));
		doAnswer(invocation -> {
			StringBuilder sb = invocation.getArgument(1);
			sb.append("key");
			return null;
		}).when(this.converter).convertOperand(eq(this.keyOperand), eq(context));
		doAnswer(invocation -> {
			StringBuilder sb = invocation.getArgument(1);
			sb.append("value");
			return null;
		}).when(this.converter).convertOperand(eq(this.valueOperand), eq(context));
		when(this.converter.getOperationSymbol(eqExpression)).thenReturn("=");
		when(this.converter.getOperationSymbol(gtExpression)).thenReturn(">");
		when(this.converter.getOperationSymbol(ltExpression)).thenReturn("<");
		// Act
		this.converter.doExpression(eqExpression, context);
		this.converter.doExpression(gtExpression, context);
		this.converter.doExpression(ltExpression, context);
		// Assert
		assertEquals("left=rightkeyvalue>leftvalue", context.toString());
		verify(this.converter, times(4)).convertOperand(eq(this.leftOperand), eq(context));
		verify(this.converter, times(2)).convertOperand(eq(this.rightOperand), eq(context));
		verify(this.converter, times(1)).convertOperand(eq(this.keyOperand), eq(context));
		verify(this.converter, times(1)).convertOperand(eq(this.valueOperand), eq(context));
	}

	@Test
	@Tag("valid")
	void emptyStringBuilderContextReceivesExpressionContent() {
		// Arrange
		Expression eqExpression = new Expression(Filter.ExpressionType.EQ, this.leftOperand, this.rightOperand);
		StringBuilder context = new StringBuilder();
		assertTrue(context.length() == 0);
		doAnswer(invocation -> {
			StringBuilder sb = invocation.getArgument(1);
			sb.append("field");
			return null;
		}).when(this.converter).convertOperand(eq(this.leftOperand), eq(context));
		doAnswer(invocation -> {
			StringBuilder sb = invocation.getArgument(1);
			sb.append("'value'");
			return null;
		}).when(this.converter).convertOperand(eq(this.rightOperand), eq(context));
		when(this.converter.getOperationSymbol(eqExpression)).thenReturn(" = ");
		// Act
		this.converter.doExpression(eqExpression, context);
		// Assert
		assertFalse(context.length() == 0);
		assertEquals("field = 'value'", context.toString());
		verify(this.converter, times(1)).convertOperand(this.leftOperand, context);
		verify(this.converter, times(1)).getOperationSymbol(eqExpression);
		verify(this.converter, times(1)).convertOperand(this.rightOperand, context);
	}

	private static class TestableNeo4jVectorFilterExpressionConverter extends Neo4jVectorFilterExpressionConverter {

		@Override
		protected void doNot(Expression expression, StringBuilder context) {
			// Mock implementation for testing
		}

		@Override
		protected void convertOperand(Filter.Operand operand, StringBuilder context) {
			// Mock implementation for testing
		}

		@Override
		protected String getOperationSymbol(Expression expression) {
			// Mock implementation for testing
			return "";
		}

	}

}